name: Deploy on kubernetes
on:
    workflow_call:
      inputs:
        enviroment-name:
          type: string
          required: true
        enviroment-url:
          type: string
          required: true

jobs:
    deploy:
        name: "Deploy"
        runs-on: Ubuntu-latest
        environment: 
          name: ${{ inputs.enviroment-name }}
          url: ${{ inputs.enviroment-url }}
        steps:
            - name: Getting code
              uses: actions/checkout@v4

            - name: Azure Login
              uses: azure/login@v1
              with:
                creds: ${{ secrets.AZURE_CREDENTIALS }}

            - name: context config
              uses: azure/k8s-set-context@v4
              with:
                method: kubeconfig
                kubeconfig: ${{ secrets.K8S_CONFIG }}
            
            - name: Update Deployment
              run: "sed -i 's/hoost: homolog.amavelantonio.com/host: ${{ vars.BASE_URL }}/g' k8s/deployment.yaml"

            - name: Deploy on Kubernentes
              uses: Azure/k8s-deploy@v5
              with:
                namespace: ${{secrets.K8S_NAMESPACE}}
                manifests: |
                    k8s/deployment.yaml
                images: |
                    ${{ secrets.DOCKERHUB_USERNAME}}/project-devops-pro:${{github.run_number}}