name: Pipeline CI/CD
run-name: Worflow did build by ${{ github.actor }} 


on:
    workflow_dispatch:
    push:
        branches:
            - main

jobs:
    build:
        name: Build
        runs-on: ubuntu-latest
        steps:
            - name: getting code of project
              uses: actions/checkout@v4
            - name: Setup dotnet
              uses: actions/setup-dotnet@v4
              with:
                dotnet-version: "8.0.300"
            - name: Run build command
              working-directory: ./src
              run: dotnet build Review-Filmes.sln