name: Pipeline CI/CD
run-name: Build by ${{ github.actor }} 

on:
    workflow_dispatch:
    push:
        branches:
            - main

jobs:
    build:
        name: Build
        runs-on: ubuntu-latest
        steps:
            - name: getting code of project
              uses: actions/checkout@v4
            - name: Setup dotnet
              uses: actions/setup-dotnet@v4
              with:
                dotnet-version: "8.0.300"
            - name: Run build command
              working-directory: ./src
              run: dotnet build Review-Filmes.sln
    tests:
      needs: [build]
      uses: AmavelAntonio/desafio-cicd-devopsPro/.github/workflows/tests.yaml@main
      secrets: inherit

    release:
         name: making release project
         runs-on: ubuntu-latest
         needs: [tests]
         steps:
            - name: Getting project code
              uses: actions/checkout@v4
            - name: Analyze DockerFile
              uses: hadolint/hadolint-action@v3.1.0
              with:
                dockerfile: ./src/Review-Filmes.Test.EndToEnd/Dockerfile
                failure-threshold: error

            - name: Docker login
              uses: docker/login-action@v3
              with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_PWD}}

            - name: Building and push image docker
              uses: docker/build-push-action@v6
              with:
                push: true
                context: ./src
                file: src/Review-Filmes.Test.EndToEnd/Dockerfile
                tags: |
                    ${{secrets.DOCKERHUB_USERNAME}}/project-devops-pro:latest
                    ${{ secrets.DOCKERHUB_USERNAME}}/project-devops-pro:${{github.run_number}}
            
            - name: Running trivy
              uses: aquasecurity/trivy-action@0.23.0
              with:
                scan-type: 'image'
                image-ref: ${{ secrets.DOCKERHUB_USERNAME}}/project-devops-pro:${{github.run_number}}
                format: sarif
                output: trivy-docker-result.sarif
                severity: 'CRITICAL,HIGH,MEDIUM,LOW,UNKNOWN'

            - name: Upload trivy file to github
              uses: github/codeql-action/upload-sarif@v3
              with: 
                category: docker-result
                sarif_file: trivy-docker-result.sarif

    deploy-homolog:
      needs: [release]
      uses: AmavelAntonio/desafio-cicd-devopsPro/.github/workflows/deploy.yaml@main
      secrets: inherit
      with:
        enviroment-name: homolog
        enviroment-url: http://homolog.amavelantonio.com

    teste-e2e:
      name: Test End to End
      runs-on: ubuntu-latest
      needs: [deploy-homolog]
      environment: 
        name: homolog
      container:
        image: fabricioveronez/webdriver-dotnet:chrome
        env:
          BASE_URL: "http://${{ vars.BASE_URL }}"
      steps:
        - name: Getting code of project
          uses: actions/checkout@v4

        - name: Run test end to end
          working-directory: ./src
          run: dotnet test ./src/Review-Filmes.Test.EndToEnd/Review-Filmes.Test.EndToEnd.csproj

    deploy-producao:
      needs: [teste-e2e]
      uses: AmavelAntonio/desafio-cicd-devopsPro/.github/workflows/deploy.yaml@main
      secrets: inherit
      with:
        enviroment-name: producao
        enviroment-url: http://producao.amavelantonio.com