name: Pipeline CI/CD
run-name: Build by ${{ github.actor }} 


on:
    workflow_dispatch:
    push:
        branches:
            - main

jobs:
    build:
        name: Build
        runs-on: ubuntu-latest
        steps:
            - name: getting code of project
              uses: actions/checkout@v4
            - name: Setup dotnet
              uses: actions/setup-dotnet@v4
              with:
                dotnet-version: "8.0.300"
            - name: Run build command
              working-directory: ./src
              run: dotnet build Review-Filmes.sln
    tests:
      needs: [build]
      uses: AmavelAntonio/desafio-cicd-devopsPro/.github/workflows/tests.yaml@main
      secrets: inherit

    release:
         name: making release project
         runs-on: ubuntu-latest
         needs: [tests]
         steps:
            - name: Getting project code
              uses: actions/checkout@v4
            - name: Docker login
              uses: docker/login-action@v3
              with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_PWD}}
            - name: Building and push image docker
              uses: docker/build-push-action@v6
              with:
                push: true
                context: ./src
                file: src/Review-Filmes.Test.EndToEnd/Dockerfile
                tags: |
                    ${{secrets.DOCKERHUB_USERNAME}}/project-devops-pro:latest
                    ${{ secrets.DOCKERHUB_USERNAME}}/project-devops-pro:${{github.run_number}}